spring.application.name=demo

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/pfmisv3
spring.datasource.username=postgres
spring.datasource.password=cuongkute97
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=day_la_secret_key_cua_ban_it_nhat_32_ky_tu_nhe
jwt.expiration=86400000

# Server
server.port=8080